### ISSUE TITLE
Last tag contains too many PRs

### ISSUE THREAD

**Issue by SteveEasley** [skywinder/github-changelog-generator#291] opened 2015-10-11 00:19 UTC
Running into an issue with the output file. I am running with `github_changelog_generator -t ... --max-issues=250` on a private repo. It is successfully appending the output of my HISTORY.md. This HISTORY file was generated with github_changelog_generator earlier (and the most recent 30 days of tags removed for testing). The issue is the first tag that is put on top of the HISTORY.md content after running the above command contains more PRs that it should. Its basically a copy of all PRs that didnt match the earlier tags. i.e. If the earlier tags matched up to 100 PRs, then the last tag contains 150 PRs (250-100=150)

The reason I am wanting to use HISTORY.md this way is because our private repo is large. It contains 1800+ PRs (and growing), and 250+ tags. As it is I cant run without the `max-issues` param because the thread/async code used by github_changelog_generator instantly gives github API rate limit warnings. Not to mention its very slow to run the command. So my plan was once a month "move" CHANGELOG.md to HISTORY.md in order to limit the scope of what it needs to do. Does that sound like a covered use case?

Here is the output of the command:

```
{:tag1=>nil,
 :tag2=>nil,
 :date_format=>"%Y-%m-%d",
 :output=>"CHANGELOG.md",
 :base=>"HISTORY.md",
 :issues=>true,
 :add_issues_wo_labels=>true,
 :add_pr_wo_labels=>true,
 :pulls=>true,
 :filter_issues_by_milestone=>true,
 :author=>true,
 :unreleased=>true,
 :unreleased_label=>"Unreleased",
 :compare_link=>true,
 :enhancement_labels=>["enhancement", "Enhancement"],
 :bug_labels=>["bug", "Bug"],
 :exclude_labels=>
  ["duplicate",
   "question",
   "invalid",
   "wontfix",
   "Duplicate",
   "Question",
   "Invalid",
   "Wontfix"],
 :max_issues=>250,
 :simple_list=>false,
 :verbose=>true,
 :header=>"# Change Log",
 :merge_prefix=>"**Merged pull requests:**",
 :issue_prefix=>"**Closed issues:**",
 :bug_prefix=>"**Fixed bugs:**",
 :enhancement_prefix=>"**Implemented enhancements:**",
 :git_remote=>"origin",
 :token=>"hidden value",
 :user=>"...",
 :project=>"phoenix"}

Found 285 tags                                                         
Fetching tags dates: 31/31       
Sorting tags...
Received issues: 270                                                   
Fetching merged dates: 1817                                            
Filtered pull requests: 243
Filtered issues: 1
Fetching events for issues and PR: 244                                 
Fetching closed dates for issues: Done!
Generating log...
Done!
```

**Comment by thorpep138** [comment] 2016-02-12 16:53
I'm also getting the first tag containing more PRs than it should -- namely those that don't match a previous tag. Can someone look into this?

**Comment by Sloy** [comment] 2016-09-01 10:42
Same here. I'm not using `--max-issues` but rather `--since-tag`. It's including all PRs in the first tag.

**Comment by thorsteneckel** [comment] 2016-11-04 22:59
Should be a duplicate of #304 and fixed with PR https://github.com/skywinder/github-changelog-generator/pull/438 .

**Comment by thorsteneckel** [comment] 2016-11-12 10:01
Feel free to reopen or leave feedback. Should be changed since 14.1.

**Closed by thorsteneckel** 2016-11-12 10:01 UTC
