### ISSUE TITLE
Some PRs logged for the wrong releases

### ISSUE THREAD

**Issue by hunner** [skywinder/github-changelog-generator#617] opened 2018-01-26 17:08 UTC
1f68ef8 causes many PRs to be logged in the changelog incorrectly.

One problem caused by this this is because the `merged_at` date (on github's PR api) can be 1+ seconds later than the merge commit date because the PR is closed after the merge commit is pushed. This matters because if the merge commit of a PR is the tagged SHA then that PR is considered part of the next release (it's merged_at time is later than the date of the tagged SHA).

Another issue I haven't found the root cause yet is that some commits that are rebased may be mentioned as being in a later release, such as #274 and #275 ; #274 went out in 1.8.4 and #275 in 1.8.5, and all 1.15.x tags currently incorrectly place this in 1.8.5.

This should be fixed before 1.15.0 goes out. Otherwise changelogs generated with 1.14.x or earlier will be incorrectly reorganized.

**Comment by ekohl** [comment] 2018-02-13 17:47
Isn't this a duplicate of https://github.com/skywinder/github-changelog-generator/issues/497?

**Comment by hunner** [comment] 2018-02-13 18:12
@ekohl I think that evaluating the git history solely on timestamps is leading to several weird behaviors. We can't change that for issues (maybe milestones are best for those) but can use the actual git history for PRs. I am taking a stab at this in #619

**Comment by hunner** [comment] 2018-02-16 18:25
For reference, this was from #504 but also predated that.

**Closed** 2018-04-05 02:25 UTC
