### ISSUE TITLE
Request for being a collaborator

### ISSUE THREAD

**Issue by Lucashuang0802** [skywinder/github-changelog-generator#509] opened 2017-05-20 19:44 UTC
😃

**Comment by skywinder** [comment] 2017-05-21 18:32
@Lucashuang0802 Thank you very much for you active position! Much appreciated. For now, @olleolleolle is the boss. 

p.s.
it's Duplicate of #272
Feel free to continue the discussion there. 
Cheers! 😉

**Closed by skywinder** 2017-05-21 18:32 UTC
